=== Chelgham-Zinedine/projet-xml/voyage.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="offres">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="offre" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>



    <xs:element name="offre"  type="offreType"/>
    <xs:complexType name="offreType">
        <xs:sequence>
            <xs:choice minOccurs="0">
                <xs:element ref="colonie_de_vacances"/>
                <xs:element ref="voyage_scolaire"/>
                <xs:element ref="immersion_famille_accueil"/>
            </xs:choice>
            <xs:element ref="langues"/>
            <xs:element ref="destination"/>
            <xs:element name="activites_sportives" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="activites_culturelles" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="date" type="xs:string"/>
            <xs:element ref="client"/>
        </xs:sequence>
        <xs:attribute name="type" type="TypeOffre" use="required"/>
    </xs:complexType>

    <xs:simpleType name="TypeClient">
        <xs:restriction base="xs:string">
            <xs:enumeration value="famille"/>
            <xs:enumeration value="adulte"/>
            <xs:enumeration value="enfant"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TypeOffre">
        <xs:restriction base="xs:string">
            <xs:enumeration value="colonie"/>
            <xs:enumeration value="scolaire"/>
            <xs:enumeration value="accueil"/>
            <xs:enumeration value="classique"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="personne">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prenom" type="xs:string"/>
            <xs:element name="age" type="xs:integer"/>
            <!-- Autres éléments spécifiques à une personne -->
        </xs:sequence>
    </xs:complexType>

    <xs:element name="client">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="personne">
                    <xs:attribute name="type" type="TypeClient" use="required"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="langues">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="langue" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="destination">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ville" type="xs:string"/>
                <xs:element name="pays" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="colonie_de_vacances" type="colonie_de_vacancesType"/>
    <xs:complexType name="colonie_de_vacancesType">
        <xs:sequence>
            <xs:element name="moniteurs" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="personne"/>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:element name="voyage_scolaire">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="matieres"/>
                <xs:element ref="enseignants"/>
                <xs:element ref="accompagnateurs"/>
                <xs:element name="nombre_eleves" type="xs:int"/>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="matiere_key">
            <xs:selector xpath="matieres/matiere"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="matiere_keyref" refer="matiere_key">
            <xs:selector xpath="enseignants/enseignant/matiere"/>
            <xs:field xpath="@ref-matiere"/>
        </xs:keyref>
    </xs:element>


    <xs:element name="immersion_famille_accueil" type="immersion_famille_accueilType"/>
    <xs:complexType name="immersion_famille_accueilType">
        <xs:sequence>
            <xs:element name="famille_accueil">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nom" type="xs:string"/>
                        <xs:element name="nombre_de_place" type="xs:int"/>
                        <xs:element name="nationalite" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="matieres" type="matieresType"/>
    <xs:complexType name="matieresType">
        <xs:sequence>
            <xs:element name="matiere" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nom" type="xs:string"/>
                        <xs:element name="evaluation" type="xs:boolean"/>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:element name="enseignants" type="enseignantsType"/>
    <xs:complexType name="enseignantsType">
        <xs:sequence>
            <xs:element name="enseignant" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="personne">
                            <xs:sequence>
                                <xs:element name="matiere-enseignee">
                                    <xs:complexType>
                                        <xs:attribute name="ref-matiere" type="xs:ID" use="required"/>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:element name="accompagnateurs" type="accompagnateursType"/>
    <xs:complexType name="accompagnateursType">
        <xs:sequence>
            <xs:element name="accompagnateur" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="personne">
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>



</xs:schema>

=== Chelgham-Zinedine/projet-xml/agence_sejour_linguistique_bd.xml
<?xml version="1.0" encoding="UTF-8"?>
<offres xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="voyage.xsd">
    <offre type="classique">
        <langues>
            <langue>Anglais</langue>
        </langues>
        <destination>
            <ville>Londres</ville>
            <pays>Royaume-Uni</pays>
        </destination>
        <activites_sportives>Football</activites_sportives>
        <activites_culturelles>Visite du British Museum</activites_culturelles>
        <dates>
            <debut>2023-07-15</debut>
            <fin>2023-09-15</fin>
        </dates>
        <client type="famille">
            <nom>Dupont</nom>
            <prenom>Paul</prenom>
            <age>46</age>
        </client>
    </offre>
    <offre type="classique">
        <langues>
            <langue>Anglais</langue>
        </langues>
        <destination>
            <ville>Londres</ville>
            <pays>Royaume-Uni</pays>
        </destination>
        <activites_sportives>Football</activites_sportives>
        <activites_culturelles>Visite du British Museum</activites_culturelles>
        <dates>
            <debut>2022-02-15</debut>
            <fin>2022-03-15</fin>
        </dates>
        <client type="famille">
            <nom>Dupont</nom>
            <prenom>Paul</prenom>
            <age>46</age>
        </client>
    </offre>
    <offre type="classique">
        <langues>
            <langue>Espagnol</langue>
        </langues>
        <destination>
            <ville>Barcelone</ville>
            <pays>Espagne</pays>
        </destination>
        <activites_sportives>Football</activites_sportives>
        <activites_culturelles>Visite du British Museum</activites_culturelles>
        <dates>
            <debut>2023-08-30</debut>
            <fin>2023-10-30</fin>
        </dates>
        <client type="famille">
            <nom>Dupont</nom>
            <prenom>Paul</prenom>
            <age>46</age>
        </client>
    </offre>
    <offre type="classique">
        <langues>
            <langue>Allemand</langue>
            <langue>Francais</langue>
        </langues>
        <destination>
            <ville>Berlin</ville>
            <pays>Allemagne</pays>
        </destination>
        <activites_sportives>Volley-ball</activites_sportives>
        <activites_culturelles>Visite du mur de Berlin</activites_culturelles>
        <dates>
            <debut>2023-01-24</debut>
            <fin>2023-02-10</fin>
        </dates>
            <client type="adulte">
                <nom>Dubois</nom>
                <prenom>Marie</prenom>
                <age>28</age>
            </client>
    </offre>
    <offre type="scolaire">
        <voyage_scolaire>
            <matieres>
                <matiere id='m0'>
                    <nom>Histoire</nom>
                    <evaluation>true</evaluation>
                </matiere>
                <matiere id='m1'>
                    <nom>Langues étrangères</nom>
                    <evaluation>true</evaluation>
                </matiere>
            </matieres>
            <enseignants>
                <enseignant>
                    <nom>Girard</nom>
                    <prenom>Lucie</prenom>
                    <age>23</age>
                    <matiere-enseignee ref-matiere="m0"/>
                </enseignant>
                <enseignant>
                    <nom>Bichon</nom>
                    <prenom>Thomas</prenom>
                    <age>45</age>
                    <matiere-enseignee ref-matiere="m1"/>
                </enseignant>
            </enseignants>
            <accompagnateurs>
                <accompagnateur>
                    <nom>Clerc</nom>
                    <prenom>Clara</prenom>
                    <age>18</age>
                </accompagnateur>
                <accompagnateur>
                    <nom>Mitou</nom>
                    <prenom>Ludivine</prenom>
                    <age>35</age>
                </accompagnateur>
            </accompagnateurs>
            <nombre_eleves>25</nombre_eleves>
        </voyage_scolaire>
        <langues>
            <langue>Espagnol</langue>
            <langue>Catalan</langue>
        </langues>
        <destination>
            <ville>Madrid</ville>
            <pays>Espagne</pays>
        </destination>
        <activites_sportives>Football</activites_sportives>
        <activites_culturelles>Visite du musée du Prado</activites_culturelles>
        <dates>
            <debut>2023-06-08</debut>
            <fin>2023-09-08</fin>
        </dates>
        <client type="enfant">
            <nom>Moreau</nom>
            <prenom>Jules</prenom>
            <age>14</age>
        </client>
    </offre>
    <offre type="accueil">
        <immersion_famille_accueil>
            <famille_accueil>
                <nom>Leclerc</nom>
                <nombre_de_place>2</nombre_de_place>
                <nationalite>française</nationalite>
            </famille_accueil>
        </immersion_famille_accueil>
        <langues>
            <langue>Francais</langue>
            <langue>Anglais</langue>
        </langues>
        <destination>
            <ville>Paris</ville>
            <pays>France</pays>
        </destination>
        <activites_culturelles>Visite de la Tour Eiffel, Promenade en bateau-mouche sur la Seine</activites_culturelles>
        <dates>
            <debut>2023-12-07</debut>
            <fin>2023-12-28</fin>
        </dates>
        <client type="famille">
            <nom>Dupont</nom>
            <prenom>Julie</prenom>
            <age>35</age>
        </client>
    </offre>
    <offre type="colonie">
        <colonie_de_vacances>
            <moniteurs>
                <nom>Leblanc</nom>
                <prenom>Antoine</prenom>
                <age>26</age>
            </moniteurs>
            <moniteurs>
                <nom>Martin</nom>
                <prenom>Lucas</prenom>
                <age>32</age>
            </moniteurs>
        </colonie_de_vacances>
        <langues>
            <langue>Anglais</langue>
            <langue>Espagnol</langue>
        </langues>
        <destination>
            <ville>Barcelone</ville>
            <pays>Espagne</pays>
        </destination>
        <activites_sportives>Surf, Kayak, Beach-volley</activites_sportives>
        <dates>
            <debut>2023-05-30</debut>
            <fin>2023-10-24</fin>
        </dates>
        <client type="enfant">
            <nom>Smith</nom>
            <prenom>Lucie</prenom>
            <age>11</age>
        </client>
    </offre>
</offres>
